[feat] Make commit message configurable
repobee/repobee-sanitizer pull request #133
Opened 2021-02-23 18:55 UTC by tohanss

Fix #131

2021-02-23 20:55 UTC, slarse commented
@tohanss You're failing style checks, and this branch is not up-to-date. Don't forget to sync with upstream before you start working on new stuff.

2021-03-06 15:02 UTC, slarse commented on tests/test_ext_commands.py
> +        )
Use `shlex.split()` instead

2021-03-06 15:02 UTC, slarse commented
Ping @tohanss

2021-03-13 12:35 UTC, slarse commented
Ping @tohanss

2021-04-26 12:31 UTC, tohanss commented
Locally, master claimed to be up to date but it seemed to have updated anyway. All should be well now!

2021-05-02 09:10 UTC, slarse requested changes
Two very minor comments, after that LGTM

2021-05-02 09:10 UTC, slarse commented on tests/test_ext_commands.py
> +        # hashtag instead of whitespace
Outdated comment
```suggestion
```

2021-05-02 09:10 UTC, slarse commented on tests/test_ext_commands.py
> +        assert commit.message == (commit_message + "\n")
If we don't care about trailing and leading whitespace, I'd do this instead:

```suggestion
        assert commit.message.strip() == commit_message.strip()
```

2021-05-08 20:25 UTC, slarse approved these changes
LGTM! Nice feature :)

2021-05-08 20:25 UTC, merged